const WORD_LIST = [
  {
    id: 1,
    difficulty: "easy",
    worth: 1,
    words: [
      "Hair Cut",
      "Sewing",
      "Playing Guitar",
      "Painting your nails",
      "Ride a bike",
      "Putting on Makeup",
      "Swimming",
      "Playing Soccer",
      "Juggle",
      "Dreaming",
      "Hopscotch",
      "Backwards",
      "Arm wrestle",
      "Dancing",
      "Robot",
      "Smiling",
      "Jumping Jacks",
      "Stop",
      "Pinch",
      "Applause",
      "Pray",
      "Skipping",
      "Elephant",
      "Monkey",
      "Brushing teeth",
      "Airplane",
      "Ringpop",
      "Ping Pong",
      "Playing Piano",
      "Tickle",
    ],
  },

  {
    id: 2,
    difficulty: "medium",
    worth: 2,
    words: [
      "Pedicure",
      "Hitch Hike",
      "Flip",
      "Playing Baseball",
      "Dentist",
      "Ironing Clothes",
      "Using a jackhammer",
      "Sleep Walking",
      "Riding a Skateboard",
      "Kneel",
      "Chomping food",
      "Photographer",
      "Surfing",
      "Kangaroo",
      "Karate",
      "Hula Hooping",
      "Whispering",
      "Seesaw",
      "Blind",
      "Twist",
    ],
  },

  {
    id: 3,
    difficulty: "hard",
    worth: 3,
    words: [
      "Baking",
      "Folding Laundry",
      "Curling Hair",
      "Using Chopsticks",
      "Riding a Carousel",
      "Skiing",
      "Mowing a Lawn",
      "Food Fight",
      "Finger Painting",
      "Watching a Scary Movie",
      "Reading a Newspaper",
      "Funnybone",
      "Michael Jackson",
    ],
  },
];

export default WORD_LIST;
